//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWork.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLists
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductLists()
        {
            this.ProductListItems = new HashSet<ProductListItems>();
        }
    
        public int ProductListID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ListName { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ProductPageID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductListItems> ProductListItems { get; set; }
        public virtual UserInfos UserInfos { get; set; }
        public virtual ProductPage ProductPage { get; set; }
        public virtual UserInfos UserInfos1 { get; set; }
    }
}
