//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWork.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfos()
        {
            this.Orders = new HashSet<Orders>();
            this.ProductLists = new HashSet<ProductLists>();
            this.ProductLists1 = new HashSet<ProductLists>();
            this.ProductPage = new HashSet<ProductPage>();
            this.Product = new HashSet<Product>();
        }
    
        public int UserId { get; set; }
        public int IDCardTypeID { get; set; }
        public Nullable<int> UserIDCard { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.TimeSpan> CreateTime { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual IDCardType IDCardType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductLists> ProductLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductLists> ProductLists1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPage> ProductPage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}
